### ISSUE TITLE
Display the current YunoHost version

### ISSUE THREAD

**Issue by jeromelebleu** [YunoHost/moulinette-yunohost#11]
The ``--version`` argument is not working anymore but it should be available. The version could be updated in the actions map directly each time a new release is tagged.

**Comment by julienmalik** [comment]
Should be better done at debian packaging time ? That way tagging does not require to not forget to modify a version file...

Anyway fixing this is important as the current code is buggy (thanks pylint) at two places :
* https://github.com/YunoHost/moulinette-yunohost/blob/unstable/lib/yunohost/app.py#L327
* https://github.com/YunoHost/moulinette-yunohost/blob/unstable/lib/yunohost/app.py#L411
where the __version__ variable is undefined

**Comment by chtixof** [comment]
`yunohost -v` and `yunohost --version` are still not working under the later version (sorry I could not figure out which :)  
Could you suggest a workaround to display the version ?  
Thanks

**Comment by jeromelebleu** [comment]
@chtixof: Yes, sorry about that. The reason is that YunoHost is made of several packages with different versions, so we have to discuss which one should be displayed with `yunohost -v`.
As a workaround, you can use:
`$ dpkg -s moulinette-yunohost | awk '/^Version: /{print $2}'`

**Comment by chtixof** [comment]
@jeromelebleu Thanks and hope the version counter will go on increasing in the future years.
