### ISSUE TITLE
Wrong regular expression in pattern_email with tld more than 6 characters

### ISSUE THREAD

**Issue by florianbeisel** [YunoHost/moulinette-yunohost#46]
When setting up an installation on a new GTLD (.hosting) you cannot add a user because the regular expression used in ``pattern_email`` (I think in ``actionsmap/yunohost.yml`` fails on those domain names). So, YunoHost is not usable with those domain names.

Adding a user fails with the error message:
> Invalid Argument 'mail': Must be a valid email address (e.g. someone@domain.org)

Information on the new GTLDs can be found on [ICANNWiki](http://icannwiki.com/All_New_gTLD_Applications)

## Steps to reproduce
* Setup with Domain ``bla.hosting``
* Add User  
* Fails with error message

**Comment by Kloadut** [comment]
Note that the pattern is wrong on the SSOwat portal too
https://github.com/Kloadut/SSOwat/blob/daily/helpers.lua#L595
