### ISSUE TITLE
Update moulinette from 2.0-rc~megusta11 to 2.2.0 fail

### ISSUE THREAD

**Issue by Jibec** [YunoHost/moulinette-yunohost#61]
Hi,

I did an update today has i noticed a few stables updates of yunohost, but it criticaly failed ;)
I think one dependency jumped, sorry for the long log copy/paste, and thanks for your help

Here is the log /var/log/apt/history.log :

Start-Date: 2015-05-10  17:27:08
Install: libluajit-5.1-2:amd64 (2.0.3+dfsg-3~bpo70+1, automatic), lua-rex-pcre:amd64 (2.6.0-2, automatic), yunohost-config-metronome:amd64 (2.2.0, automatic), postfix-pcre:amd64 (2.9.6-2, automatic), libconfuse-common:amd64 (2.7-4, automatic), libnss-mdns:amd64 (0.10-3.2, automatic), libavahi-common-data:amd64 (0.6.31-2, automatic), libavahi-core7:amd64 (0.6.31-2, automatic), libluajit-5.1-common:amd64 (2.0.3+dfsg-3~bpo70+1, automatic), libconfuse0:amd64 (2.7-4, automatic), libdaemon0:amd64 (0.14-2, automatic), avahi-daemon:amd64 (0.6.31-2, automatic), udisks-glue:amd64 (1.3.4-1, automatic), libavahi-common3:amd64 (0.6.31-2, automatic), lua-bitop:amd64 (1.0.2-1, automatic)
Upgrade: lua-socket:amd64 (2.0.2-8, 3.0~rc1-3~bpo70+1+b1), ssowat:amd64 (2.0-rc~megusta3, 2.2.0), yunohost-config-mysql:amd64 (2.0-rc1~megusta1, 2.2.0), yunohost-config-amavis:amd64 (2.0-rc1~megusta1, 2.2.0), yunohost-config-nginx:amd64 (2.0-rc1~megusta7, 2.2.0), yunohost:amd64 (2.0-rc1~megusta1, 2.2.0), yunohost-config-dovecot:amd64 (2.0-rc1~megusta1, 2.2.0), yunohost-config-others:amd64 (2.0-rc1~megusta3, 2.2.0), init-system-helpers:amd64 (1.11~bpo70.1, 1.18~bpo70+1), nginx-common:amd64 (1.4.4-1~bpo70+1, 1.6.2-5~bpo70+1), metronome:amd64 (3.5~megusta4, 3.6-6), nginx-extras:amd64 (1.4.4-1~bpo70+1, 1.6.2-5~bpo70+1), moulinette-yunohost:amd64 (2.0-rc~megusta22, 2.2.0), yunohost-config-postfix:amd64 (2.0-rc1~megusta5, 2.2.0), yunohost-predepends:amd64 (2.0-rc1~megusta1, 2.2.0), moulinette:amd64 (2.0-rc~megusta11, 2.2.0), yunohost-config-slapd:amd64 (2.0-rc1~megusta2, 2.2.0), yunohost-admin:amd64 (2.0-rc1~megusta17, 2.2.1), yunohost-config:amd64 (2.0-rc1~megusta2, 2.2.0)
Remove: libc-client2007e:amd64 (2007f~dfsg-2), ruby1.8-dev:amd64 (1.8.7.358-7.1+deb7u3), liblua5.1-event0:amd64 (0.4.1-2), python-twisted-mail:amd64 (12.0.0-1), python-twisted-bin:amd64 (12.0.0-1), pkg-config:amd64 (0.26-1), python-gobject-2:amd64 (2.28.6-10), python-foolscap:amd64 (0.6.4-1), tahoe-lafs:amd64 (1.9.2-1), python-twisted-lore:amd64 (12.0.0-1), libcrypto++9:amd64 (5.6.1-6), python-twisted-news:amd64 (12.0.0-1), rubygems:amd64 (1.8.24-1), liblua5.1-0-dev:amd64 (5.1.5-4+deb7u1), python-nevow:amd64 (0.10.0-4), python-mock:amd64 (0.8.0-3), python-zope.interface:amd64 (3.6.1-3), python-twisted-conch:amd64 (12.0.0-1), python-twisted-words:amd64 (12.0.0-1), libgirepository-1.0-1:amd64 (1.32.1-1), python-twisted-web:amd64 (12.0.0-1), python-twisted:amd64 (12.0.0-1), python-serial:amd64 (2.5-2.1), python-udiskie:amd64 (2.0-rc1~megusta2), libreadline6-dev:amd64 (6.2+dfsg-0.1), python-pycryptopp:amd64 (0.5.29-1), ruby1.8:amd64 (1.8.7.358-7.1+deb7u3), python-pam:amd64 (0.4.2-13), python-gi:amd64 (3.2.2-2), libtinfo-dev:amd64 (5.9-10), haste:amd64 (1.0-beta4~megusta1), mlock:amd64 (2007f~dfsg-2), python-dbus-dev:amd64 (1.1.1-1), libidn11-dev:amd64 (1.25-2), python-dbus:amd64 (1.1.1-1), yunohost-config-tahoe:amd64 (2.0-rc1~megusta1), python-twisted-core:amd64 (12.0.0-1), python-simplejson:amd64 (2.5.2-1), gir1.2-glib-2.0:amd64 (1.32.1-1), python-gobject:amd64 (3.2.2-2), php5-imap:amd64 (5.4.39-0+deb7u2), python-twisted-names:amd64 (12.0.0-1), wwwconfig-common:amd64 (0.2.2), liblua5.1-0:amd64 (5.1.5-4+deb7u1), python-twisted-runner:amd64 (12.0.0-1), libruby1.8:amd64 (1.8.7.358-7.1+deb7u3), libjs-jquery:amd64 (1.7.2+dfsg-1), python-xmpp:amd64 (0.5.1rc1), python-zfec:amd64 (1.4.5-2), yunohost-apps:amd64 (1.0~yunohost9), javascript-common:amd64 (8), libreadline-dev:amd64 (6.2+dfsg-0.1)
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2015-05-10  17:30:50

Here is the aptitude log :

Paramétrage de moulinette-yunohost (2.2.0) ...
update-rc.d: using dependency based boot sequencing
[ ok ] Restarting API: YunoHost:.
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 160, in <module>
    print_json=PRINT_JSON, use_cache=USE_CACHE)
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 117, in cli
    moulinette.run(args, print_json)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 197, in run
    ret = self.actionsmap.process(args, timeout=5)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 458, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/app.py", line 906, in app_ssowatconf
    for item in app_settings['skipped_uris'].split(','):
AttributeError: 'NoneType' object has no attribute 'split'
dpkg: erreur de traitement de moulinette-yunohost (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
dpkg: des problèmes de dépendances empêchent la configuration de yunohost-admin :
 yunohost-admin dépend de moulinette-yunohost ; cependant :
 Le paquet moulinette-yunohost n'est pas encore configuré.

dpkg: erreur de traitement de yunohost-admin (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de yunohost-config :
 yunohost-config dépend de yunohost-admin ; cependant :
 Le paquet yunohost-admin n'est pas encore configuré.
 yunohost-config dépend de moulinette-yunohost ; cependant :
 Le paquet moulinette-yunohost n'est pas encore configuré.

dpkg: erreur de traitement de yunohost-config (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de yunohost :
 yunohost dépend de yunohost-config ; cependant :
 Le paquet yunohost-config n'est pas encore configuré.

dpkg: erreur de traitement de yunohost (--configure) :
 problèmes de dépendances - laissé non configuré
Des erreurs ont été rencontrées pendant l'exécution :
 moulinette-yunohost
 yunohost-admin
 yunohost-config
 yunohost
Appuyez sur Entrée pour continuer.

**Comment by jeromelebleu** [comment]
Thanks for the bug report!

**Comment by Jibec** [comment]
thanks for fixing it, how to I apply it on my server ? it's still not working today after update with aptitude, any other thing to do ?
