### ISSUE TITLE
YunoHost admin GUI doesn't accept password

### ISSUE THREAD

**Issue by finster-** [YunoHost/moulinette-yunohost#63]
Somehow the admin GUI does not accept my admin password, it keeps saying "wrong password".
But it works with the admin cli, the password is accepted...

**Comment by opi** [comment]
without revealing your password, is there any special character in it ? something different from alpha-numeric character ...

**Comment by finster-** [comment]
I use characters like:
` & { * - _ ;" `

**Comment by opi** [comment]
@jeromelebleu any guess ?

**Comment by jeromelebleu** [comment]
@finster- I tried with each of these character and I don't have any issue...

**Comment by finster-** [comment]
Thats the thing :) It worked (via gui) for a few weeks and than i was only able to use ssh... 

Am 11. Juli 2015 22:30:27 MESZ, schrieb "Jérôme Lebleu" <notifications@github.com>:
>@finster- I tried with each of these character and I don't have any
>issue...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/YunoHost/moulinette-yunohost/issues/63#issuecomment-120660047

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jeromelebleu** [comment]
I don't see any reason why it would stop working suddenly, there is no - at least not a lot - magic inside! :)

Did you upgrade packages on your server meanwhile? Also, you can maybe check that it's not coming from your client - e.g. change in your keyboard layout - and be sure that the password you typed is the right one... even if it seems improbable...

**Comment by finster-** [comment]
No magic...im disappointed :) 
I had to reinstall my yunohost so i can't test it right now, but i tried the same password right away by ssh and it worked. There is someone else at the yunohost forum who has the same problem, maybe he/she can somehow help to reproduce the issue. Sorry! If it happens to me again, ill post again.

**Comment by jeromelebleu** [comment]
No problem! Tell us if it happens again, in the meantime I'll close this issue... Feel free to re-open it if you have more information, thanks!
