### ISSUE TITLE
Backup fails if "archives" not present inside /home/yunohost.backup

### ISSUE THREAD

**Issue by ZeHiro** [YunoHost/moulinette-yunohost#65]
Hello,

It the folder "archives" is not present inside /home/yunohost.backup, the command : 
sudo yunohost backup create
fails

I ghuess this happens on 2.0 installs upgraded to 2.2 (the directory  /home/yunohost.backup was already here).
Thanks

**Comment by jeromelebleu** [comment]
Hi, do you have an error message or some logs please? It's difficult to guess what happened whithout that... Thanks!

**Comment by ZeHiro** [comment]
sudo yunohost backup create                                    Traceback (most recent call last):
  File "/usr/bin/yunohost", line 160, in <module>
    print_json=PRINT_JSON, use_cache=USE_CACHE)
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 117, in cli
    moulinette.run(args, print_json)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 197, in run
    ret = self.actionsmap.process(args, timeout=5)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 458, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/backup.py", line 68, in backup_create
    if name in backup_list()['archives']:
  File "/usr/lib/moulinette/yunohost/backup.py", line 300, in backup_list
    archives = os.listdir(archives_path)
OSError: [Errno 2] No such file or directory: '/home/yunohost.backup/archives'

**Comment by jeromelebleu** [comment]
Thanks for reporting this bug!

**Comment by ZeHiro** [comment]
You're welcome. Shouldn't the fix include also the creation of the directory "archives" , as it is the default directory for backups?

**Comment by jeromelebleu** [comment]
Nope, it's already done here: https://github.com/YunoHost/moulinette-yunohost/blob/unstable/lib/yunohost/backup.py#L167

**Comment by Kloadut** [comment]
@jeromelebleu Actually the `/home/yunohost.backup` directory is not created, we should use `makedirs` instead of `makedir`

**Comment by ZeHiro** [comment]
/home/yunohost.backup is created, bu the sub directory archives is not

**Comment by jeromelebleu** [comment]
@Kloadut Yes it is, but here: https://github.com/YunoHost/moulinette-yunohost/blob/unstable/lib/yunohost/backup.py#L114 :)

@ZeHiro And yes it should be created here: https://github.com/YunoHost/moulinette-yunohost/blob/unstable/lib/yunohost/backup.py#L167

I know it's some kind of treasure hunt!

**Comment by ZeHiro** [comment]
OK. Cool. Thanks

**Comment by jeromelebleu** [comment]
Anyway, I think those directories should be created with the Debian package and not in the moulinette scripts. It would be easier to manage YunoHost uninstallation for example...
