### ISSUE TITLE
skipped_uris and unprotected_uris ignored when app installed at root of domain

### ISSUE THREAD

**Issue by ZeHiro** [YunoHost/moulinette-yunohost#68]
Hi,
when I install an app at the root of a domain, the skipped_uris or unprotected_uris are ignored in the generation of the configurations.
dpkg -l | grep ssowat
ii  ssowat                           2.2.2                              all          SSOWAT

Here is the "problem" conf file : 

domain: test.mydomain.tld
path: /
skipped_uris: /

(skipped_uris can be longer, like /api/greader.php, for freshrss)

Thanks

**Comment by M5oul** [comment]
Hi, could you move that issue to [SSowat repo](https://github.com/Kloadut/SSOwat/issues/new).

**Comment by ZeHiro** [comment]
Yes I can. But to me it us related to the generation of the conf.json file. I did tests since then and when manually motifying the /etc/ssowat/config.json file and adding the proper skipped_urls object (test.mydomain.tld) to the file, ssowat works fine. So i guess it comes from the moulinette.

**Comment by M5oul** [comment]
Ok.

**Comment by mbugeia** [comment]
Hi, maybe it's the desired behavior see https://github.com/YunoHost/moulinette-yunohost/issues/52

**Comment by ZeHiro** [comment]
Hmm, I don't know. @Kloadut ?

From what I have unterstood, skipped_urls (inside conf.json) are bulit like that : 

skipped_urls = domain + path + skipped_uris

It happens that if path = '/' , skipped_urls are not included in the conf.json

**Comment by Kloadut** [comment]
@ZeHiro Yes, this looks like a bug.  domain + path + skipped_uris should work even if path is "/"

**Comment by Kloadut** [comment]
It is coming from here https://github.com/YunoHost/moulinette-yunohost/blob/unstable/lib/yunohost/app.py#L910

If the path is "/", then it is shrinked to "" (empty string).

**Comment by ZeHiro** [comment]
in this case empty string should work fine. e.g. : 
domain = test.domain.tld
path = /
skipped_uris = /

If I  want to have a public app (like a blog) 
The skipped_urls should be 
skipped_urls = test.domain.tld

**Comment by Kloadut** [comment]
yes, I was just pointing out where the bug came from

**Comment by ZeHiro** [comment]
The current implementation seems good :)

By the way, here : 

https://github.com/YunoHost/moulinette-yunohost/blob/unstable/lib/yunohost/app.py#L931

Shouldn't be : 

skipped_urls.extend([ domain + '/yunohost/admin', domain + '/yunohost/api'])

otehrwies you get n (number of domains) times the same thing

**Comment by Kloadut** [comment]
Yup, this is another bug :)

**Comment by Kloadut** [comment]
Do not hesitate to send a pull request though. You can try on your YunoHost instance by editing apps.py in `/usr/lib/moulinette/yunohost/` , and then run `yunohost app ssowatconf`in CLI.

It shouldn't be too hard to fix :-)

**Comment by ZeHiro** [comment]
Let's try python!

**Comment by ZeHiro** [comment]
OK, I found what my problem was, a error was raised on checking if the app was installed and manifest.json was missing. Which stopped the generation of ALL skipped/unprotected uris, normal. 
What is not checked, is thas the uri starts with  ΅/" should is be done?
