### ISSUE TITLE
Home folder is not created at user addition

### ISSUE THREAD

**Issue by jeromelebleu** [YunoHost/moulinette-yunohost#70]
The command at https://github.com/YunoHost/moulinette-yunohost/blob/unstable/lib/yunohost/user.py#L193 seems to be not properly executed since the home folder is not created when a user is added.

**Comment by polytan02** [comment]
I confirm this issue on my newly installed yunohost. 

It seem that I folder is created when I use shellinabox and try to connect with the user. Obviously the connection fails as no yunohost user can connect via ssh. However the folder is created.
