### ISSUE TITLE
Add Dnsmasq service

### ISSUE THREAD

**Issue by M5oul** [YunoHost/moulinette-yunohost#81]
https://github.com/YunoHost/moulinette-yunohost/blob/unstable/data/other/services.yml.
I can not find where logs are.
https://github.com/YunoHost/yunohost-admin/issues/105

**Comment by jeromelebleu** [comment]
Fixed with https://github.com/YunoHost/moulinette-yunohost/commit/47d8b7f8af8fe1cb3dd221701424befd31ebbc7f
